### ISSUE TITLE
Nightly builds roadmap

### ISSUE THREAD

**Issue by Zimmi48** [coq/platform#108]
Providing nightly Coq builds would simply mean having a webpage where users can download a binary package corresponding to the latest version of Coq master branch.
This should include at least the packages we provide now for released versions (MacOS, Windows 32 bits and Windows 64 bits) but it would be cool to provide more (e.g. a Debian / Ubuntu `.deb` binary package, a Nix package with a binary cache, etc).

Nightly builds are useful to ensure that all our users have the possibility of testing development (alpha) versions, including those who are on platforms where compiling Coq from sources is harder. In particular, developers of Coq packages we test in CI must be able to run their packages with the latest version of Coq master.
Additionally, providing a pre-compiled Linux package (`.deb` or Nix) would help gain build time for people testing their package on CI with the development version of Coq.

We are already quite close to providing nightly builds. Here are the steps I see:

- [x] Build MacOS and Windows packages on CI.
- [x] *(optional)* Build Linux binary packages on CI (done with Nix).
- [ ] Give a precise version number to these packages. See coq/coq#483.
      What is the current status of this PR? @ejgallego do you intend to take care of finishing it and do you think that Dune is going to help here?
- [ ] Choose where to host these packages. Because Travis doesn't provide native build artifact support, the MacOS package currently uses bintray. With a proper version number, it would make sense to use this platform for nightly builds and we could upload Windows package over there as well.

**Comment by MSoegtropIMC** [comment]
I wanted to follow up on this issue and ask what the final conclusion / request is.

Possible are:
- run the .dev pick in daily CI on selected or all platforms
- create a new .ci pick which takes the versions from Coq CI for those packages shared between Coq CI and Platform on selected or all platforms

In order to avoid confusion with CI status, I would probably run these as separate actions.

**Comment by Zimmi48** [comment]
I think that for Coq master, using the .dev picks or the CI picks would be pretty close because both of them are usually tracking the main development branches and are aimed to keep building with Coq dev.

**Comment by MSoegtropIMC** [comment]
Indeed I had a look at (https://github.com/coq/coq/blob/master/dev/ci/ci-basic-overlay.sh) and it seems to be 100% on master - afair it was not always like this.

So I guess we can drop the idea of a separate CI pick.

The remaining question then is for which platforms such a nightly build should be done. All?

**Comment by Zimmi48** [comment]
It was always close to this state. This is not the case when using a `v8.X` branch. (Then reusing the CI pick makes sense.)

>The remaining question then is for which platforms such a nightly build should be done. All?

If it is easy to generate and make the installers downloadable, then probably yes. That being said, since the nightly builds are not for beginners, and that the experienced users should probably prefer the Platform scripts, providing the .dev pick through the scripts only would probably also be fine.

**Comment by MSoegtropIMC** [comment]
It is easy to do this, but it costs quite a bit of server time (5..6h per platform) and in the end roughly 100..200 kg CO2 per year (assuming the German energy mix).

I would then suggest that I just reenable the dev build in CI, so that I know when it gets broken.

**Comment by Zimmi48** [comment]
Agreed that it's probably not worth. Let's just make sure that we document somewhere that this dev build is available and tested.

**Comment by MSoegtropIMC** [comment]
Doing this I probably also should put the older builds into a weekly build. They don't break regularly, but they do break (e.g. I recently did a patch to OCamlfind where I used library functions introduced in OCaml 4.13, which broke the older Coq versions since they picked up this patch).

**Comment by MSoegtropIMC** [comment]
Triaging note: this is mostly done - the main issue is the signing of the installers, which INRIA is still working on.
