### ISSUE TITLE
Tracker issue for 8.14 package tag creation

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#139]
This issue exists to track the issues on the package upstream repos to create tags for Coq 8.14.

There is no manual interaction required - this ticket is referenced in all package issues and automatically updated with the package issue status.

Discussions should take place in the individual upstream issues.

### Various issues:

- [x] Coq 8.14.1 is out
- [x] include the Snap patches for Coq 8.13.2
- [x] https://github.com/ocaml/opam-repository/issues/19243

### Issue links to non github projects
- [x] (https://gitlab.mpi-sws.org/iris/stdpp/-/issues/119)
- [x] (https://gitlab.mpi-sws.org/iris/iris/-/issues/435)
- [x] (https://gitlab.inria.fr/coquelicot/coquelicot/-/issues/4)
- [x] (https://gitlab.inria.fr/coqinterval/interval/-/issues/7)
- [x] (https://gitlab.inria.fr/flocq/flocq/-/issues/17)
- [x] (https://gitlab.inria.fr/gappa/coq/-/issues/9)
- [x] (https://gitlab.inria.fr/fpottier/menhir/-/issues/55)

### Opam updates to consider
- [x] coq-aac-tactics (https://github.com/coq/opam-coq-archive/pull/1853)
- [x] coq-equations (https://github.com/coq/opam-coq-archive/pull/1958)

### Local Opam packages to remove:
- [x] https://github.com/ocaml/opam-repository/pull/20537

### Packages which need some work:
- [x] coq-prime needs support for the proof generator tool
- [x] coq-hammer needs support for provers

**Comment by MSoegtropIMC** [comment]
Closed since the 8.14 pick is delivered in 2022.01
