### ISSUE TITLE
Tracker issue for 8.15 package tag creation

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#193]
This issue exists to track the issues on the package upstream repos to create tags for Coq 8.15.

There is no manual interaction required - this ticket is referenced in all package issues and automatically updated with the package issue status.

Discussions should take place in the individual upstream issues.

## ToDo:
- [x] Update OCaml to 4.13+flambda if possible - see (https://github.com/coq/coq/issues/11652)
- [x] Coqhammer: update smoke test to check ATP availability
- [x] Give Windows installers similar names as Mac installers and change default install folder
- [x] Add 8.14~2022.03 pick 
- [x] Try to fix ott for windows and / or fix smoke test kit for ott / coq-ott
- [x] Use 8.15 in snap package
- [x] Review release notes
- [x] Think about switching all picks to lablgtk3.3.1.2 (See https://github.com/coq/coq/issues/15857, https://github.com/coq/coq/issues/15486)
- [x] Update dev pick
- [x] Check if lablgtk3.3.1.2 needs the same patch as lablgtk3.3.1.1 on Windows (CoqIDE works fine without the patch)
- [x] Move Coq relation algebra after coq-aac-tactics.
- [x] Create coq-interval-flocq3 and coq-gappa-flocq3 packages
- [x] Adjust synopsis / description in flocq3 legacy packages
- [x] Recreate readme files for new picks 

### Issue links to non github projects
- [x] [coq-stdpp](https://gitlab.mpi-sws.org/iris/stdpp/-/issues/129)
- [x] [coq-coquelicot](https://gitlab.inria.fr/coquelicot/coquelicot/-/issues/5)
- [x] [coq-flocq](https://gitlab.inria.fr/flocq/flocq/-/issues/20)
- [x] [coq-interval](https://gitlab.inria.fr/coqinterval/interval/-/issues/9)
- [x] [coq-gappa](https://gitlab.inria.fr/gappa/coq/-/issues/10)
- [x] [coq-menhirlib](https://gitlab.inria.fr/fpottier/menhir/-/issues/63)
- [x] [coq-iris](https://gitlab.mpi-sws.org/iris/iris/-/issues/443)

### Updates to be done
- [x] https://github.com/mattam82/Coq-Equations/issues/471
- [x] https://github.com/unicoq/unicoq/issues/66
- [x] https://github.com/Mtac2/Mtac2/issues/350
- [x] https://github.com/LPCIC/coq-elpi/issues/327
- [x] https://github.com/coq-community/coq-dpdgraph/issues/95
- [x] https://github.com/HoTT/HoTT/issues/1619#issuecomment-1018866387
- [x] https://github.com/lukaszcz/coqhammer/issues/120
- [x] https://github.com/math-comp/analysis/issues/519
- [x] https://github.com/math-comp/math-comp/issues/843
- [x] https://github.com/UniMath/UniMath/issues/1442
- [x] https://github.com/QuickChick/QuickChick/issues/269 test and reenable QuickChick
- [x] Consider creating z3_tptp.4.8.14

### Local opam packages to be removed
- [x] https://github.com/coq/opam-coq-archive/pull/2047
- [x] https://github.com/coq/opam-coq-archive/pull/2050
- [x] https://github.com/coq/opam-coq-archive/pull/2051
- [x] https://github.com/coq/opam-coq-archive/pull/2052
- [x] https://github.com/coq/opam-coq-archive/pull/2053
- [x] https://github.com/coq/opam-coq-archive/pull/2054
- [x] https://github.com/coq/opam-coq-archive/pull/2055
- [x] https://github.com/coq/opam-coq-archive/pull/2058
- [x] https://github.com/coq/opam-coq-archive/pull/2063
- [x] https://github.com/coq/opam-coq-archive/pull/2064
- [x] https://github.com/coq/opam-coq-archive/pull/2071
- [x] https://github.com/coq/opam-coq-archive/pull/2135
- [x] https://github.com/coq/opam-coq-archive/pull/2133
- [x] Check if more can be removed

### Issues to be fixed
- [x] https://github.com/coq/platform/issues/186
- [x] Provide more info for https://github.com/ocaml/opam/issues/5021#issuecomment-1019513701

**Comment by MSoegtropIMC** [comment]
Looks all good.
