### ISSUE TITLE
Tracker issue for 8.17 package tag creation

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#335]
This issue exists to track the issues on the package upstream repos to create tags for Coq 8.17.

This ticket is referenced in all package issues.

Discussions should take place in the individual upstream issues.

### Issue links to non github projects
- [x] https://gitlab.mpi-sws.org/iris/stdpp/-/issues/172
- [x] https://gitlab.inria.fr/coquelicot/coquelicot/-/issues/7
- [x] https://gitlab.inria.fr/flocq/flocq/-/issues/22
- [x] https://gitlab.inria.fr/coqinterval/interval/-/issues/13
- [x] https://gitlab.inria.fr/gappa/coq/-/issues/12
- [x] https://gitlab.inria.fr/fpottier/menhir/-/issues/69
- [x] https://gitlab.inria.fr/fbesson/itauto/-/issues/30
- [x] https://gitlab.mpi-sws.org/iris/iris/-/issues/516

### Updates to be done

- [x] https://github.com/HoTT/Coq-HoTT/issues/1727
- [x] Coq 8.17.0 + remove opam dev repo
- [x] E-prover 3.0 (postponed since there is no official release as yet)

### Local opam packages to be removed
- [x] coq-metacoq.1~preview+8.17 and sub packages
- [x] coq-vst-32.2.12

### Local opam packages to be merged upstream
- [x] gappa.1.4.1 https://github.com/ocaml/opam-repository/pull/23433
- [x] z3_tptp.4.11.2 https://github.com/ocaml/opam-repository/pull/23434
- [x] **KEEP-LOCAL** (won't be merged upstream) ocamlfind relocation patch https://github.com/ocaml/ocamlfind/issues/60
- [x] coq-coqprime https://github.com/coq/opam-coq-archive/pull/2496
- [x] coq-compcert-32 https://github.com/coq/opam-coq-archive/pull/2493#event-8708041257
- [x] coq-math-classes https://github.com/coq/opam-coq-archive/pull/2506
- [x] coq-hott https://github.com/coq/opam-coq-archive/pull/2508
- [x] **KEEP-LOCAL** (missing in MinGW repo ) elpi
- [x] coq-mathcomp-word https://github.com/coq/opam-coq-archive/pull/2509
- [x] coq-reglang https://github.com/coq/opam-coq-archive/pull/2510#event-8756545113
- [x] coq-unimath https://github.com/coq/opam-coq-archive/pull/2537
- [x] coq-unicoq https://github.com/coq/opam-coq-archive/pull/2538
- [x] coq-mtac2 https://github.com/coq/opam-coq-archive/pull/2539
- [x] coq-record-update https://github.com/coq/opam-coq-archive/pull/2541
- [x] fiat-crypto & dependencies https://github.com/coq/opam-coq-archive/pull/2540

### Issues to be fixed

- [x] Replace smoke test file for fingroup with mathcomp/fingroup/quotient.v https://github.com/math-comp/math-comp/issues/892#issuecomment-1471629615
- [x] CI: Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.  (delayed, creates issue)
- [x] Add path length check on root path on Windows (for serapi). (delayed, creates issue)

### Checklist
- [x] Update release in documentation
- [x] Add new picks to documentation
- [x] Update auto generated documentation
- [x] Ensure that release builds for MacOS, Snap and Windows include large packages
- [x] Ensure Mac installers work for older MacOS (by inspecting otool dump)

**Comment by ejgallego** [comment]
Closing as this seems completed.
