### ISSUE TITLE
Tracker issue for 8.18 pick creation

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#372]
This issue exists to track the issues on the package upstream repos to create tags for Coq 8.18.

This ticket is referenced in all package issues.

Discussions should take place in the individual upstream issues.

### Issue links to non github projects

- [x] https://gitlab.mpi-sws.org/iris/stdpp/-/issues/198
- [x] https://gitlab.inria.fr/coquelicot/coquelicot/-/issues/9
- [x] https://gitlab.inria.fr/flocq/flocq/-/issues/23
- [x] https://gitlab.inria.fr/coqinterval/interval/-/issues/14
- [x] https://gitlab.inria.fr/gappa/coq/-/issues/13
- [x] https://gitlab.inria.fr/fpottier/menhir/-/issues/73
- [x] https://gitlab.inria.fr/fbesson/itauto/-/issues/32
- [x] https://gitlab.mpi-sws.org/iris/iris/-/issues/544
- [x] https://gitlab.inria.fr/gappa/gappa/-/issues/13

### Updates to be done

- [x] Update mathcomp-word to 3.0 - see https://github.com/coq/opam/pull/2844#issuecomment-1822778094
- [x] Update libhyps - see https://github.com/Matafou/LibHyps/issues/13

### Local opam packages to be removed
- [x] coq-unicoq.1.6+8.18
- [x] coq-math-classes.8.18.0
- [x] coq-unimath.20231010
- [x] coq-compcert.3.13.1
- [x] coq-corn.8.18.0
- [x] coq-mtac2.1.4+8.18
- [x] coq-ott.0.33 see https://github.com/ocaml/opam-repository/pull/24942

### Local opam packages to be merged upstream

- [x] coq-deriving.0.1.1
- [x] coq-extructures.0.3.1
- [x] coq-simple-io.1.8.0

### Issues to be fixed
- [x] Provide some sort of smoke test for serapi (it failed to install in a few cases)
- [x] Somehow restrict the number of picks shown - either by a fixed number or by sort index 0 (this is still OK in current release => delayed)
- [x] Smoke Test coq-libhyps
- [x] Smoke Test coq-extructures
- [x] Think about providine a dependency graph as part of the doc
- [x] Coq Ott is disabled on WIndows
- [x] Coq patch see https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Anomaly.3A.20bad.20vernac.20extend/near/403585445 : decided to not include a patch, since this did not work for a longer time (not in 8.17 at least).

### Checklist
- [x] Update release in documentation
- [x] Add new picks to documentation
- [x] Update auto generated documentation
- [x] Ensure that release builds for MacOS, Snap and Windows include large packages
- [x] Ensure Mac installers work for older MacOS (by inspecting otool dump)
