### ISSUE TITLE
Tracker issue for 8.19 package tag creation

### ISSUE THREAD

**Issue by rtetley** [coq/platform#405]
This issue exists to track the issues on the package upstream repos to create tags for Coq 8.19.

This ticket is referenced in all package issues.

Discussions should take place in the individual upstream issues.

### Issue links to non github projects
- [x] https://gitlab.mpi-sws.org/iris/stdpp/-/issues/206
- [x] https://gitlab.inria.fr/coquelicot/coquelicot/-/issues/10
- [x] https://gitlab.inria.fr/flocq/flocq/-/issues/24
- [x] https://gitlab.inria.fr/coqinterval/interval/-/issues/16
- [x] [coq-gappa](https://gitlab.inria.fr/gappa/coq/-/issues/14)
- [x] [gappa](https://gitlab.inria.fr/gappa/gappa/-/issues/15)
- [x] https://gitlab.inria.fr/fpottier/menhir/-/issues/74
- [x] https://gitlab.inria.fr/fbesson/itauto/-/issues/34
- [x] [coq-iris](https://gitlab.mpi-sws.org/iris/iris/-/issues/567)
- [x] [coq-iris-heap-lang](https://gitlab.mpi-sws.org/iris/iris/-/issues/568)

### Checklist
- [x] Update release in documentation
- [x] Add new picks to documentation
- [x] Update auto generated documentation
- [x] Ensure that release builds for MacOS, Snap and Windows include large packages
- [x] Ensure Mac installers work for older MacOS (by inspecting otool dump)

**Comment by MSoegtropIMC** [comment]
Release is done.
