### ISSUE TITLE
Tracker issue for 8.20 package tag creation

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#449]
This issue exists to track the issues on the package upstream repos to create tags for Coq 8.20.

This ticket is referenced in all package issues.

Discussions should take place in the individual upstream issues.

### Updates to be done
- [ ] EProver 3.2 (private communication with Stephan Schulz)

### Local opam packages to be removed
- [ ] coq-unimath.20240923

### Checklist
- [ ] Update release in documentation
- [ ] Add new picks to documentation
- [ ] Update auto generated documentation
- [ ] Ensure that release builds for MacOS, Snap and Windows include large packages
- [ ] Ensure Mac installers work for older MacOS (by inspecting otool dump)
