### ISSUE TITLE
Coq Platform master package failures 2021/01

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#58]
This is a meta issue to track failures of packages in the Coq Platform nightly master build which first appeared in January 2021.

- Menhir
  - [x] [upstream issue](https://gitlab.inria.fr/fpottier/menhir/-/issues/49) created
  - [x] fixed upstream
  - [x] verified
- coq-elpi
  - [x] [upstream issue](https://github.com/LPCIC/coq-elpi/issues/203) created
  - [x] fixed usptream
  - [x] verified 
- gappa (macOS with Homebrew)
  - [x] [upstream issue](https://gitlab.inria.fr/gappa/gappa/-/issues/7) created
  - [x] fixed upstream (main opam repo)
  - [x] fixed upstream (MinGW opam repo) 
  - [x] verified
