### ISSUE TITLE
Coq Platform master package failures 2021/02

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#78]
This is a meta issue to track failures of packages in the Coq Platform nightly master build which first appeared in February 2021.
Only issues which are not fixed within 1 day are mentioned here.

- Coqc segfault compling coq interval test cases.
  - [x] reported upstream (https://github.com/coq/coq/pull/13867)
  - [x] fixed
  - [x] verified / affected package (coq-interval) reenabled

- Windows: opam pkg-config installation issue
  - [x] reported upstream (https://github.com/ocaml/opam-repository/pull/18177)
  - [x] fixed
  - [x] verified / local patch removed

**Comment by gares** [comment]
I marked the segfault problem fixed as per 8.13.1 release

**Comment by MSoegtropIMC** [comment]
I changed it back to non verified since I have to reenable Coq Interval to verify it. I will do some master cleanup tomorrow.
